### ISSUE TITLE
Using autocomplete (jqueryui)

### ISSUE THREAD

**Issue by phorvath84** [modularcode/modular-admin-html#28]
Dear all,

I'm trying to implement autocomplete from jqueryui into modular-admin.
Unfortunately it seems that putting jquery script into the template conflicts. 
Scripts of jquery are added into the header, app.js and vendor.js into the end.
Console shows "autocomplete is not a function".

If I delete app.js and vendor.js then all is working with the jquery code.

Any idea to solve this problem?

Rgds

**Comment by modularcoder** [comment]
Hi @phorvath84 

As per build system configuration, all vendor script files installed via bower are concatenated together.
There's a plugin called main bower files, which detects vendor dependencies main files.
You probably need to install jqueryui via bower.

After that please refer this two files and their comments
https://github.com/modularcode/modular-admin-html/blob/master/build/tasks/app-scripts.js
https://github.com/modularcode/modular-admin-html/blob/master/build/paths/vendor.js

Otherwise you can just include the jqueryui script tag after vendor.js in pages

Regards
Gevorg

**Comment by phorvath84** [comment]
Hi Gevorg,

thanks for your response.

Meanwhile I have learned the above by trying and trying over hours.

Thanks for your support!

Rgds,
Patrick

**Comment by modularcoder** [comment]
Hi Patrick
I'm happy you could figure it out )

indeed, these bould tools and package managers are bit confusing in the beginning )

Let me know if you'll need any help

Regards
Gevorg
