### ISSUE TITLE
Source version

### ISSUE THREAD

**Issue by krosoftware** [modularcode/modular-admin-html#41]
Hello and thank you for great template.
Is there any option to use Bootstrap and other libraries directly instead using vendor.js?
With other words, I want to upgrade to Bootstrap v4. alpha 6 - how to do that?
Thank you.

**Comment by modularcoder** [comment]
Hi @krosoftware 
Thanks for your feedback.

Vendor dependencies are managed via bower package manager.

Please see this file
https://github.com/modularcode/modular-admin-html/blob/master/bower.json

You need to update bootstrap version there and reinstall bower packages. 
After that rebuild the project. + Update the breaking changes that might occur after bootstrap update.

Also I strongly dis-advice modifying the content of the ```dist/``` folder directly, because It's compiled version and isn't suitable for adjustments. It's better to work inside ```src/``` folder.

Please see this section in docs>
https://github.com/modularcode/modular-admin-html#development

Thanks
Gevorg
