### ISSUE TITLE
Angular 4 / Angular-Cli testing

### ISSUE THREAD

**Issue by duard** [modularcode/modular-admin-html#46]
I just import this template to my Angular APP 
https://github.com/duard/appone if someone need to test.

**Comment by modularcoder** [comment]
Hi @duard !
Great to know that you've started porting ModularAdmin to angular.
I've cloned your project locally, but it seems to be blank so far.

Thanks
Gevorg

P.S. If you'll be able to port ModularAdmin to Angular, I'll be happy to refer your project as a community version of ModularAdmin in docs.

**Comment by salvdev** [comment]
@duard Did you manage to get Metis Menu to work with Angular? Been converting my project over Modular with good success but got stuck on getting Metis Menu properly initializing. All Menus are open by default instead of closed and clicking on them sends you back to the root app instead of expanding the menu.

**Comment by modularcoder** [comment]
Closing this issue due to long inactivity
